# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_catalog',
            name='catalog_name',
            field=models.TextField(default='April catalog by Tanishq', verbose_name='Catalog Name and Desc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='design_catalog',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Design photo'),
        ),
    ]
