# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0002_auto_20180423_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutting_phase',
            options={'verbose_name': 'Cutting Phase', 'verbose_name_plural': 'Cutting Phases'},
        ),
        migrations.AlterModelOptions(
            name='design_catalog',
            options={'verbose_name': 'Design', 'verbose_name_plural': 'Designs'},
        ),
        migrations.AlterModelOptions(
            name='embedding_phase',
            options={'verbose_name': 'Embedding Phase', 'verbose_name_plural': 'Embedding Phases'},
        ),
        migrations.AlterModelOptions(
            name='hallmark_verification',
            options={'verbose_name': 'Hallmark Verification Phase', 'verbose_name_plural': 'Hallmark Verification Phases'},
        ),
        migrations.AlterModelOptions(
            name='jewel',
            options={'verbose_name': 'Jewel', 'verbose_name_plural': 'Jewels'},
        ),
        migrations.AlterModelOptions(
            name='jewellery',
            options={'verbose_name': 'Jewellery', 'verbose_name_plural': 'Jewelleries'},
        ),
        migrations.AlterModelOptions(
            name='jewellery_type',
            options={'verbose_name': 'Jewellery Type', 'verbose_name_plural': 'Jewellery Types'},
        ),
        migrations.AlterModelOptions(
            name='material_purchase',
            options={'verbose_name': 'Purchase Raw Material', 'verbose_name_plural': 'Purchase Raw Materials'},
        ),
        migrations.AlterModelOptions(
            name='polishing_phase',
            options={'verbose_name': 'Polishing Phase', 'verbose_name_plural': 'Polishing Phases'},
        ),
        migrations.AlterModelOptions(
            name='raw_material_type',
            options={'verbose_name': 'Raw Material Type', 'verbose_name_plural': 'Raw Material Types'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.AlterField(
            model_name='hallmark_verification',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Verification Status'),
            preserve_default=False,
        ),
    ]
