# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0003_remove_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
