# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0004_auto_20180425_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_purchase',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
    ]
