# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jmms.models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0004_auto_20180324_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='User Name')),
                ('user_address', models.TextField(max_length=1000, verbose_name='Address')),
                ('contact_details_1', models.CharField(max_length=13, verbose_name='Phone Number 1')),
                ('contact_details_2', models.CharField(max_length=13, null=True, verbose_name='Phone Number 2')),
                ('email', models.CharField(max_length=255, verbose_name='EMail ID')),
                ('rating', jmms.models.IntegerRangeField(help_text='Rating of the User')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.UserType')),
            ],
        ),
    ]
