# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0005_auto_20180427_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallmark_verification',
            name='order_receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='Order Receive Date'),
        ),
        migrations.AlterField(
            model_name='hallmark_verification',
            name='order_send_date',
            field=models.DateField(verbose_name='Order Send Date'),
        ),
    ]
