# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0006_remove_user_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Material_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255, verbose_name='Material Name')),
                ('material_purity', models.IntegerField(verbose_name='Material Purity')),
                ('material_price', models.PositiveIntegerField(verbose_name='Material Price')),
                ('material_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Material weight')),
                ('material_purchase_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
