# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0006_auto_20180427_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting_phase',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Receive Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='embedding_phase',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Receive Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polishing_phase',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Receive Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Send Status'),
            preserve_default=False,
        ),
    ]
