# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0010_auto_20180324_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewellery_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewellery_name', models.CharField(max_length=255, verbose_name='Jewellery Name')),
                ('material_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.Raw_Material_Type')),
            ],
        ),
    ]
