# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0011_jewellery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design_Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=255, verbose_name='Design Name')),
                ('design_description', models.TextField(max_length=1000, verbose_name='Design Description')),
                ('added_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Added Date & Time')),
            ],
        ),
        migrations.AlterField(
            model_name='jewellery_type',
            name='material_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.Raw_Material_Type', verbose_name='Material Type'),
        ),
        migrations.AlterField(
            model_name='material_purchase',
            name='material_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.Raw_Material_Type', verbose_name='Material Type'),
        ),
        migrations.AlterField(
            model_name='material_purchase',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='material_purchase',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.User', verbose_name='Suplier'),
        ),
        migrations.AddField(
            model_name='design_catalog',
            name='jewellery_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.Jewellery_type', verbose_name='Jewellery Type'),
        ),
    ]
