# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0013_jewel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.Design_Catalog', verbose_name='Jewellery Design')),
                ('raw_material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.Raw_Material_Type', verbose_name='Raw Material')),
            ],
        ),
    ]
