# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0014_jewellery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutting_Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_sent', models.FloatField(default=0.0, verbose_name='Weight Sent')),
                ('lost_weight', models.FloatField(default=0.0, verbose_name='Lost Weight')),
                ('receive_weight', models.FloatField(default=0.0, verbose_name='Receive Weight')),
                ('cutting_cost', models.PositiveIntegerField(verbose_name='Cutting Cost')),
                ('sent_date', models.DateField(verbose_name='Sent Date')),
                ('receiving_date', models.DateField(verbose_name='Receive Date')),
                ('cutter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.User', verbose_name='Cutter Name')),
                ('jewellery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.Jewellery', verbose_name='Jewellery')),
            ],
        ),
    ]
