# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0018_auto_20180324_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding_phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_sent', models.FloatField(default=0.0, verbose_name='Weight Sent')),
                ('receive_weight', models.FloatField(default=0.0, verbose_name='Receive Weight')),
                ('jewel_price', models.PositiveIntegerField(verbose_name='Jewel Price')),
                ('jewel_quantity', models.PositiveIntegerField(verbose_name='Jewel Quantity')),
                ('jewel_weight', models.FloatField(default=0.0, verbose_name='Jewel Weight')),
                ('jewel_size', models.PositiveIntegerField(verbose_name='Jewel Size')),
                ('embedding_cost', models.PositiveIntegerField(verbose_name='embedding Cost')),
                ('other_cost', models.PositiveIntegerField(verbose_name='Other Cost')),
                ('sent_date', models.DateField(verbose_name='Sent Date')),
                ('receive_date', models.DateField(verbose_name='Receive Date')),
                ('embedder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.User', verbose_name='Embedder Name')),
                ('jewel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.Jewel', verbose_name='Jewel')),
                ('jewellery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.Jewellery', verbose_name='Jewellery')),
            ],
        ),
    ]
