# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0019_embedding_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polishing_phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_sent', models.FloatField(default=0.0, verbose_name='Weight Sent')),
                ('receive_weight', models.FloatField(default=0.0, verbose_name='Receive Weight')),
                ('polishing_cost', models.PositiveIntegerField(verbose_name='polishing Cost')),
                ('other_cost', models.PositiveIntegerField(verbose_name='Other Cost')),
                ('sent_date', models.DateField(verbose_name='Sent Date')),
                ('receive_date', models.DateField(verbose_name='Receive Date')),
                ('jewellery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.Jewellery', verbose_name='Jewellery')),
                ('polisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.User', verbose_name='Polisher Name')),
            ],
        ),
    ]
