# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 11:18
from __future__ import unicode_literals

from django.db import migrations
import jmms.models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0020_polishing_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=jmms.models.IntegerRangeField(default=5, help_text='Rating of the User'),
        ),
    ]
