# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 05:45
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0021_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_purchase',
            name='purchase_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='material_purchase',
            name='purchase_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Purchase Weight'),
        ),
        migrations.AlterField(
            model_name='raw_material_type',
            name='material_current_price',
            field=models.FloatField(verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='raw_material_type',
            name='material_unit',
            field=models.FloatField(verbose_name='Material Unit'),
        ),
    ]
