# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0024_remove_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting_phase',
            name='cutter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cutter Name'),
        ),
        migrations.AlterField(
            model_name='embedding_phase',
            name='embedder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Embedder Name'),
        ),
        migrations.AlterField(
            model_name='material_purchase',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Suplier'),
        ),
        migrations.AlterField(
            model_name='polishing_phase',
            name='polisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Polisher Name'),
        ),
    ]
