# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0026_auto_20180405_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
