# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0028_design_catalog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design_catalog',
            name='added_date_time',
        ),
        migrations.AddField(
            model_name='design_catalog',
            name='added_date',
            field=models.DateField(blank=True, null=True, verbose_name='Added Date'),
        ),
    ]
