# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0029_auto_20180416_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_catalog',
            name='image',
            field=models.ImageField(null=True, upload_to='jmms/images/', verbose_name='Design photo'),
        ),
    ]
