# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0032_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Design photo'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='order_send_date',
            field=models.DateField(blank=True, null=True, verbose_name='Order Send Date'),
        ),
    ]
