# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0033_auto_20180416_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallmark_Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_receive_date', models.DateField(verbose_name='Order Receive Date')),
                ('order_send_date', models.DateField(blank=True, null=True, verbose_name='Order Send Date')),
                ('verifying_cost', models.PositiveIntegerField(verbose_name='Verifying Cost')),
                ('other_cost', models.PositiveIntegerField(verbose_name='Other Cost')),
                ('weight_sent', models.FloatField(default=0.0, verbose_name='Weight Sent')),
                ('receive_weight', models.FloatField(default=0.0, verbose_name='Receive Weight')),
                ('jewellery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.Jewellery', verbose_name='Jewellery')),
            ],
        ),
    ]
