# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0034_hallmark_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallmark_verification',
            name='remark',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='seller',
            name='payment_received',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Amount of payment received'),
        ),
    ]
