# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0035_auto_20180419_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallmark_verification',
            name='jewellery_id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='jewellery_id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='design_catalog',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='design_catalog',
            name='image',
        ),
        migrations.AddField(
            model_name='design_catalog',
            name='added_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Added Date & Time'),
        ),
        migrations.DeleteModel(
            name='Hallmark_Verification',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
