# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jmms', '0036_auto_20180416_2229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='embedding_phase',
            unique_together=set([('jewellery_id', 'embedder_id', 'sent_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='hallmark_verification',
            unique_together=set([('jewellery_id', 'order_send_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='polishing_phase',
            unique_together=set([('jewellery_id', 'polisher_id', 'sent_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together=set([('seller_id', 'jewellery_id', 'order_send_date')]),
        ),
    ]
