# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='User Name')),
                ('user_address', models.TextField(max_length=1000, verbose_name='Address')),
                ('contact_details_1', models.TextField(max_length=13, verbose_name='Phone Number 1')),
                ('contact_details_2', models.TextField(max_length=13, null=True, verbose_name='Phone Number 2')),
                ('email', models.TextField(max_length=255, verbose_name='EMail ID')),
                ('rating', models.IntegerField(help_text='Rating of the User')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=255, verbose_name='User Type')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmms.UserType'),
        ),
    ]
