# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 11:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_details_1',
            field=models.CharField(max_length=13, verbose_name='Phone Number 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_details_2',
            field=models.CharField(max_length=13, null=True, verbose_name='Phone Number 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, verbose_name='EMail ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(help_text='Rating of the User', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
